[project]
name = "sovereign-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "pymupdf>=1.28.2",
    "requests>=2.34.2",
]

[project.scripts]
sovereign-rag = "sovereign_rag:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
